朴素贝叶斯分类算法处理情感分析

In [1]:
import numpy as np
import pandas as pd
import os
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')

df_angry = pd.read_csv('E:/谷歌下载/kaggle-nlp/Emotion(angry).csv')
df_happy = pd.read_csv('E:/谷歌下载/kaggle-nlp/Emotion(happy).csv')
df_sad = pd.read_csv('E:/谷歌下载/kaggle-nlp/Emotion(sad).csv')
df_main = pd.concat([df_angry, df_happy, df_sad])
df_main = df_main.reset_index(drop=True)

# Remove duplicates
df_main = df_main.drop_duplicates(subset=['content', 'sentiment'])
df_main = df_main.reset_index(drop=True)

# Remove empty data
df_main['content'].replace('', np.nan, inplace=True)
df_main = df_main.dropna(subset = ['content'])
df_main = df_main.reset_index(drop=True)

In [2]:
df_main

content sentiment
0     Sometimes I’m not angry, I’m hurt and there’s ...     angry
1                        Not available for busy people☺     angry
2     I do not exist to impress the world. I exist t...     angry
3     Everything is getting expensive except some pe...     angry
4          My phone screen is brighter than my future 🙁     angry
...                                                 ...       ...
1587  Stop crying over yesterday and start smiling f...       sad
1588  An Eye with Dust ‘n A Heart with Trust Always ...       sad
1589  Tears come from the heart and not from the brain.       sad
1590  Sometimes you have to hold your head up high, ...       sad
1591  Instead of wiping your tears, wipe away the pe...       sad

[1592 rows x 2 columns]

In [3]:
df_main.shape

(1592, 2)

In [4]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1592 entries, 0 to 1591
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   content    1592 non-null   object
 1   sentiment  1592 non-null   object
dtypes: object(2)
memory usage: 25.0+ KB


In [5]:
df = df_main.drop_duplicates(subset='content', keep="first")

In [6]:
df.shape

(1586, 2)

In [7]:
df['sentiment'].value_counts()

happy    703
angry    498
sad      385
Name: sentiment, dtype: int64

In [50]:
df['sentiment'].replace({'happy':1,'angry':0,'sad':2},inplace=True)

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

In [9]:
df['sentiment'].value_counts()

1    703
0    498
2    385
Name: sentiment, dtype: int64

In [10]:
import re
def clean_html(text):
    
    clean = re.compile('<.*?>')
    return re.sub(clean, '',text)
    
df['content']=df['content'].apply(clean_html)

E:\anada\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [11]:
def convert_lower(text):
    return text.lower()

df['content']=df['content'].apply(convert_lower)

E:\anada\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [12]:
def remove_special(text):
        x=''
        for i in text:
            if i.isalnum():
                x=x+i
            else:
                x=x+' '
        return x

df['content']=df['content'].apply(remove_special)

E:\anada\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


In [58]:
df['content']

0                     sometimes angry hurt big difference
1                                   available busy people
2       exist impress world exist live life way make h...
3       everything getting expensive except people get...
4                            phone screen brighter future
                              ...                        
1587         stop crying yesterday start smiling tomorrow
1588                  eye dust n heart trust always cries
1589                               tears come heart brain
1590    sometimes hold head high blink away tears say ...
1591         instead wiping tears wipe away people caused
Name: content, Length: 1586, dtype: object

In [13]:
import nltk
from nltk.corpus import stopwords

def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y
df['content']=df['content'].apply(remove_stopwords)

E:\anada\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]


In [14]:
def join_back(list_input):
    return " ".join(list_input)
    

df['content']=df['content'].apply(join_back)

E:\anada\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [56]:
df['content']

0                     sometimes angry hurt big difference
1                                   available busy people
2       exist impress world exist live life way make h...
3       everything getting expensive except people get...
4                            phone screen brighter future
                              ...                        
1587         stop crying yesterday start smiling tomorrow
1588                  eye dust n heart trust always cries
1589                               tears come heart brain
1590    sometimes hold head high blink away tears say ...
1591         instead wiping tears wipe away people caused
Name: content, Length: 1586, dtype: object

In [15]:
import nltk

from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()
y=[]

def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z
df['content']=df['content'].apply(stem_words)

E:\anada\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]


In [16]:
def joinback2(list_input):
    return "".join(list_input)
    


df['content']=df['content'].apply(joinback2)

E:\anada\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [17]:
df

content  sentiment
0                   sometimes angry hurt big difference          0
1                                 available busy people          0
2     exist impress world exist live life way make h...          0
3     everything getting expensive except people get...          0
4                          phone screen brighter future          0
...                                                 ...        ...
1587       stop crying yesterday start smiling tomorrow          2
1588                eye dust n heart trust always cries          2
1589                             tears come heart brain          2
1590  sometimes hold head high blink away tears say ...          2
1591       instead wiping tears wipe away people caused          2

[1586 rows x 2 columns]

In [18]:
X=df['content']

In [19]:
X

0                     sometimes angry hurt big difference
1                                   available busy people
2       exist impress world exist live life way make h...
3       everything getting expensive except people get...
4                            phone screen brighter future
                              ...                        
1587         stop crying yesterday start smiling tomorrow
1588                  eye dust n heart trust always cries
1589                               tears come heart brain
1590    sometimes hold head high blink away tears say ...
1591         instead wiping tears wipe away people caused
Name: content, Length: 1586, dtype: object

In [20]:
y=df.iloc[:,-1].values

In [22]:
y

array([0, 0, 0, ..., 2, 2, 2], dtype=int64)

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.3)

处理完数据对数据进行朴素贝叶斯处理

利用Using CountVectorizer

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1500)

In [26]:
X_train = cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [27]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [28]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [29]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score

print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.49159663865546216
Multinomial 0.7163865546218487
Bernaulli 0.6722689075630253


进行模型的测试

In [31]:
test="i am sad & depressed too"

In [32]:
test = np.array([test])
test = cv.transform(test)

In [33]:
clf2.predict(test)

array([2], dtype=int64)

利用Usiing TfidfVectorizer

In [34]:
X1=df['content']
y=df.iloc[:,-1].values

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X1,y,test_size=0.3)

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(min_df= 1, max_features=1500, strip_accents='unicode',analyzer='word',ngram_range=(1,3),stop_words='english')

In [38]:
X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()

In [39]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [40]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [41]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.5840336134453782
Multinomial 0.6512605042016807
Bernaulli 0.569327731092437


In [42]:
test="just go to jail"

In [48]:
test = np.array([df_angry['content'][0]])
test = tv.transform(test)

In [49]:
clf2.predict(test)

array([0], dtype=int64)